import { palette } from './palette';
export const semantic = {

  bg: {
    main: palette.base.white,
    weak: palette.grey[50],
    soft: palette.grey[100],
    sub: palette.grey[200],
    disable: palette.grey[300],
    disable2: palette.grey[50],

    inverse: palette.grey[950],
  overlay: 'rgba(0,0,0,0.30)',
  primary: palette.blue[500],
  'primary-hover': palette.blue[600],
  'primary-subtle': palette.blue[50],
  secondary: palette.secondary[500],
  'secondary-hover': palette.secondary[600],
  'secondary-subtle': palette.secondary[50],
  error: palette.red[500],
  'error-hover': palette.red[600],
  'error-subtle': palette.red[50],
  success: palette.green[500],
  'success-hover': palette.green[600],
  'success-subtle': palette.green[50],
  warning: palette.yellow[500],
  'warning-hover': palette.yellow[600],
  'warning-subtle': palette.yellow[50],
},
// Content (text) roles
content: {
  headline: palette.grey[950],
    title: palette.grey[800],
    subtitle: palette.grey[700],
    body1: palette.grey[600],
    body2: palette.grey[500],
  caption: palette.grey[400],
  placeholder: palette.grey[300],
  disable: palette.grey[300],
  onInverse: palette.base.white,
  primary: palette.blue[500],
  onPrimary: palette.base.white,
  secondary: palette.secondary[500],
  onSecondary: palette.base.white,
  error: palette.red[500],
  success: palette.green[500],
  warning: palette.yellow[500],
  info: palette.blue[500],
},
// Icon roles
  icon: {main: palette.grey[600],
    sub: palette.grey[400],
    disable: palette.grey[300],
    onInverse: palette.base.white,
    primary: palette.blue[500],
    onPrimary: palette.base.white,
    error: palette.red[500],
    onError: palette.base.white,
    success: palette.green[500],
    onSuccess: palette.base.white,
    warning: palette.yellow[500],
    onWarning: palette.grey[900],
  },
// Border roles
  border: {
    main: palette.grey[200],
    sub: palette.grey[300],
    divider: palette.grey[200],
    divider2: palette.grey[100],
    disable: palette.grey[100],
    primary: palette.blue[500],
    secondary: palette.secondary[500],
    error: palette.red[500],
    success: palette.green[500],
    warning: palette.yellow[500],
    info: palette.blue[500],
  },
} as const;
