name: Build & Deploy (Compose)

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  packages: write

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/memarbashi:latest

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}
          # If you have private packages, uncomment the next two lines and create repo secret NPM_TOKEN
          secrets: |
            "NPM_TOKEN=${{ secrets.NPM_TOKEN }}"
          provenance: false

deploy:
  needs: build-and-push
  runs-on: ubuntu-latest
  steps:
    - name: Checkout
      uses: actions/checkout@v4             # <-- THIS was missing

    - name: Copy docker-compose to server
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}   # root
        password: ${{ secrets.SERVER_PASSWORD }}
        port: ${{ secrets.SERVER_PORT || 22 }}
        source: "./docker-compose.yml"         # explicitly from repo root
        target: "/opt/memarbashi"

    - name: Deploy via SSH (compose pull & up)
      uses: appleboy/ssh-action@v1.1.0
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}   # root
        password: ${{ secrets.SERVER_PASSWORD }}
        port: ${{ secrets.SERVER_PORT || 22 }}
        script: |
          set -e
          mkdir -p /opt/memarbashi
          cd /opt/memarbashi
          docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
          docker compose down || true
          docker compose pull
          docker compose up -d
          docker ps --format 'table {{.Names}}\t{{.Status}}\t{{.Ports}}' | grep memarbashi || true
